name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: .backend/package-lock.json

    - name: Create .env file and add secret
      run: |
        touch .env
        echo "TEST=${{ secrets.TEST }}" > .env
      working-directory: ./backend

    - name: Restart application with PM2
      run: pm2 restart api
      working-directory: ./backend
